import 'package:flutter/material.dart';
import 'package:tangankanan/models/project.dart';
import 'package:tangankanan/models/pledge.dart';
import 'package:tangankanan/services/database_service.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:tangankanan/views/style.dart';

class PaymentPage extends StatefulWidget {
  final Project project;

  const PaymentPage({Key? key, required this.project}) : super(key: key);

  @override
  _PaymentPageState createState() => _PaymentPageState();
}

class _PaymentPageState extends State<PaymentPage> {
  final _amountController = TextEditingController();
  final _formKey = GlobalKey<FormState>();
  final _auth = FirebaseAuth.instance;

  bool _isProcessing = false;
  bool _isPaymentSuccessful = false; // Added payment success flag
  String? _selectedBank;

  final List<String> _paymentMethods = ['Online Banking', 'Debit/Credit Card'];
  final List<String> _banks = [
    'Maybank',
    'CIMB Bank',
    'RHB',
    'Public Bank',
    'AmBank',
    'Bank Islam',
    'Bank Muamalat',
    'HSBC',
    'OCBC Bank',
  ];

  @override
  void initState() {
    super.initState();
  }

  void _processPayment() async {
    if (_formKey.currentState!.validate()) {
      // Close the keyboard
      FocusScope.of(context).unfocus();

      final amount = double.parse(_amountController.text);
      final user = _auth.currentUser;

      if (user != null) {
        final pledge = Pledge(
          pledgeId: '', // This will be generated by Firestore
          userId: user.uid,
          projectId: widget.project.projectId,
          amount: amount,
          date: DateTime.now(),
          status: 'completed',
        );

        setState(() {
          _isProcessing = true;
          _isPaymentSuccessful = false; // Reset payment success flag
        });

        try {
          // Simulate payment processing
          await Future.delayed(Duration(seconds: 5));

          // On success, update the project currentFund and create a pledge
          await DatabaseService()
              .updateProjectFund(widget.project.projectId, amount);
          await DatabaseService().createPledge(pledge);
          await DatabaseService().addProjectToUserBackedProjects(
              user.uid, widget.project.projectId);
          await DatabaseService()
              .addBackerToProject(widget.project.projectId, user.uid);

          setState(() {
            _isPaymentSuccessful = true; // Set payment success flag
          });

          // Show success SnackBar
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Payment Successful!'),
              backgroundColor: Colors.green,
            ),
          );

          Navigator.pop(context);
        } catch (e) {
          print('Error processing payment: $e');
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error processing payment: $e')),
          );
        } finally {
          setState(() {
            _isProcessing = false;
          });
        }
      } else {
        // Handle user not logged in
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text('You need to be logged in to support a project.')),
        );
      }
    }
  }

  Widget _buildBankGrid() {
    final Map<String, String> bankLogos = {
      'Maybank': 'assets/bank_icon/maybank.png',
      'CIMB Bank': 'assets/bank_icon/cimb.png',
      'RHB': 'assets/bank_icon/rhb.png',
      'Public Bank': 'assets/bank_icon/public_bank.png',
      'AmBank': 'assets/bank_icon/ambank.png',
      'Bank Islam': 'assets/bank_icon/bank_islam.png',
      'Bank Muamalat': 'assets/bank_icon/bank_muamalat.png',
      'HSBC': 'assets/bank_icon/hsbc.png',
      'OCBC Bank': 'assets/bank_icon/ocbc.png',
    };

    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 3,
        childAspectRatio: 1,
        crossAxisSpacing: 10,
        mainAxisSpacing: 10,
      ),
      itemCount: _banks.length,
      itemBuilder: (context, index) {
        final bank = _banks[index];
        final isSelected = _selectedBank == bank;
        return GestureDetector(
          onTap: () {
            setState(() {
              _selectedBank = bank;
            });
          },
          child: Card(
            color:
                isSelected ? Color.fromARGB(255, 207, 232, 252) : Colors.white,
            child: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Image.asset(
                    bankLogos[bank]!,
                    height: 80,
                    width: 80,
                  ),
                  SizedBox(height: 8),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildCardForm() {
    return Column(
      children: [
        TextFormField(
          decoration: InputDecoration(labelText: 'Card Number'),
          keyboardType: TextInputType.number,
        ),
        TextFormField(
          decoration: InputDecoration(labelText: 'Expiry Date'),
          keyboardType: TextInputType.datetime,
        ),
        TextFormField(
          decoration: InputDecoration(labelText: 'CVV'),
          keyboardType: TextInputType.number,
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text('Support this project'),
      ),
      body: Stack(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Form(
              key: _formKey,
              child: Column(
                children: [
                  Text(
                    widget.project.title,
                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                  ),
                  SizedBox(height: 20),
                  TextFormField(
                    controller: _amountController,
                    decoration: InputDecoration(
                      labelText: 'Enter contribution amount',
                      prefixText: 'RM ',
                    ),
                    keyboardType: TextInputType.number,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter an amount';
                      }
                      return null;
                    },
                  ),
                  SizedBox(height: 20),
                  Expanded(
                    child: PageView.builder(
                      itemCount: _paymentMethods.length,
                      itemBuilder: (context, index) {
                        return Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Card(
                            child: Padding(
                              padding: const EdgeInsets.all(16.0),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    _paymentMethods[index],
                                    style: TextStyle(
                                        fontSize: 20,
                                        fontWeight: FontWeight.bold),
                                  ),
                                  SizedBox(height: 20),
                                  Expanded(
                                    child: index == 0
                                        ? _buildBankGrid()
                                        : SingleChildScrollView(
                                            child: _buildCardForm(),
                                          ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                  SizedBox(height: 20),
                  AppStyles.button('Confirm', _processPayment),
                  SizedBox(height: 20),
                  RichText(
                    textAlign: TextAlign.center,
                    text: TextSpan(
                      style: TextStyle(color: Colors.grey),
                      children: [
                        TextSpan(
                            text:
                                'By hitting the button confirm, you agree with the '),
                        TextSpan(
                          text: 'terms',
                          style: TextStyle(color: Colors.blue),
                        ),
                        TextSpan(text: ' and '),
                        TextSpan(
                          text: 'conditions',
                          style: TextStyle(color: Colors.blue),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          if (_isProcessing)
            Container(
              color: Colors.black.withOpacity(0.85),
              child: Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    CircularProgressIndicator(),
                    SizedBox(height: 16),
                    Text(
                      'Processing payment...',
                      style: TextStyle(color: Colors.white, fontSize: 16),
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }
}
